# Generated by Django 4.1.6 on 2023-02-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_currency_tax_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='items',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='items',
        ),
        migrations.AddField(
            model_name='discount',
            name='orders',
            field=models.ManyToManyField(to='main.order'),
        ),
        migrations.AddField(
            model_name='tax',
            name='orders',
            field=models.ManyToManyField(to='main.order'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
