# Generated by Django 4.1.6 on 2023-02-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_discount_items_remove_tax_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='orders',
        ),
        migrations.AddField(
            model_name='discount',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.AddField(
            model_name='tax',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
