# Generated by Django 4.1.6 on 2023-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_discount_orders_remove_tax_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллар')], default='RUB', max_length=3),
        ),
    ]
