# Generated by Django 4.1.6 on 2023-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='orders',
        ),
        migrations.AddField(
            model_name='discount',
            name='orders',
            field=models.ManyToManyField(to='main.order'),
        ),
        migrations.AddField(
            model_name='tax',
            name='orders',
            field=models.ManyToManyField(to='main.order'),
        ),
    ]
